services:
  mysql_db:
    image: mysql:latest  # Asegúrate de usar una versión estable
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: data_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - my_network

  setup_db:
    build: .
    command: ["python", "setup_db.py"]
    networks:
      - my_network  # Especifica la red a la que pertenece el servicio

  grafana:
  image: grafana/grafana:latest
  ports:
    - "3000:3000"
  environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin
  depends_on:
    - mysql_db
  networks:
    - my_network


networks:
  my_network:
    driver: bridge