services:
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: data_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - my_network

  setup_db:
    build: .
    command: >
      /bin/sh -c "python setup_db.py && python ETL/load_processed_data.py && python app.py"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
